AnimalRescue/Controllers/AnimalController.cs
using AnimalRescue.Exceptions;
using AnimalRescue.Models;
using AnimalRescue.Services.AnimalServices.Interfaces;
using AnimalRescue.Services.FavoriteServices.Interfaces;
using AnimalRescue.Services.FileUploadServices.Interfaces;
using AnimalRescue.Services.UserSevices.Interfaces;
using AnimalRescueDBModels.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AnimalRescue.Controllers
{
    public class AnimalController : Controller
    {
        private readonly IGetShelterAnimals _getShelterAnimals;
        private readonly IAddAnimal _addAnimal;
        private readonly IFileUpload _fileUpload;
        private readonly IGetUserByEmail _getUserByEmail;
        private readonly IGetUserFavorites _getUserFavorites;
        private readonly IDeleteAnimal _deleteAnimal;
        public string filePath;

        public AnimalController(IGetShelterAnimals getShelterAnimals,
                                IAddAnimal addAnimal,
                                IFileUpload fileUpload,
                                IGetUserByEmail getUserByEmail,
                                IGetUserFavorites getUserFavorites,
                                IDeleteAnimal deleteAnimal)
        {
            _getShelterAnimals = getShelterAnimals;
            _addAnimal = addAnimal;
            _fileUpload = fileUpload;
            _getUserByEmail = getUserByEmail;
            _getUserFavorites = getUserFavorites;
            _deleteAnimal = deleteAnimal;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult DisplayShelterPets(ShelterModel shelter)
        {
            if (User.Identity.IsAuthenticated) 
            {
                var user = _getUserByEmail.GetUserModel(User.Identity.Name);
                var favoritesList = _getUserFavorites.GetFavorites(user.Id);

                ViewData["SelectedUserFavorites"] = favoritesList;
            }

            var animals = _getShelterAnimals.GetAnimals(shelter.Id);
            ViewData["ShelterAnimals"] = animals;

            return View();
        }

        [HttpGet]
        [Authorize(Roles ="admin")]
        public IActionResult AddPet(ShelterModel shelter) 
        {
            ViewData["ShelterId"] = shelter.Id.ToString();

            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<ActionResult> AddPet(AnimalModel animal)
        {
            var repoPath = $"wwwroot\\Repo\\Animals\\{animal.ShelterId}";

            if (animal.File != null)
            {
                filePath = await _fileUpload.UploadFileAsync(animal.File, repoPath, animal.Id.ToString());
            }
            else
            {
                throw new FileUploadExeption("You have not uploaded an image!!!Please do this!!!");
            }
            
            animal.Id = Guid.NewGuid();
            animal.PhotoFileName = $"{animal.Id}{Path.GetExtension(animal.File.FileName)}";

            _addAnimal.CreateAnimal(animal);
            
            return Redirect("/Shelter/Index");
        }


        public IActionResult DeleteAnimal(AnimalModel animalModel) 
        {
            _deleteAnimal.DeleteAnimal(animalModel);

            return Redirect("/Shelter/Index");
        }
    }
}

AnimalRescue/Controllers/ShelterController.cs
using AnimalRescue.Models;
using AnimalRescue.Services.AnimalServices.Interfaces;
using AnimalRescue.Services.ShelterServices;
using AnimalRescue.Services.ShelterServices.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AnimalRescue.Controllers
{
    public class ShelterController : Controller
    {
        private readonly IAddShelter _addShelter;
        private readonly IGetAllShelters _getAllShelters;
        private readonly IDeleteShelter _deleteShelter;
        private readonly IEditShelter _editShelter;
        private readonly IGetShelterById _getShelterById;

        public ShelterController(IAddShelter addShelter,
                                 IGetAllShelters getAllShelters,
                                 IDeleteShelter deleteShelter,
                                 IEditShelter editShelter,
                                 IGetShelterById getShelterById)
        {
            _addShelter = addShelter;
            _getAllShelters = getAllShelters;
            _deleteShelter = deleteShelter;
            _editShelter = editShelter;
            _getShelterById = getShelterById;
        }

        [HttpGet]
        public IActionResult Index()
        {
            ViewData["AllShelters"] = _getAllShelters.GetAllShelters();
            return View();
        }

        [Authorize(Roles ="admin")]
        [HttpGet]
        public IActionResult AddShelter() 
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public IActionResult AddShelter(ShelterModel model)
        {
            _addShelter.CreateNewShelter(model);
            return Redirect("/Shelter/Index");
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public IActionResult RemoveShelter(ShelterModel shelterModel) 
        {
            _deleteShelter.DeleteShelter(shelterModel.Id);

            return Redirect("/Shelter/Index");
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public IActionResult EditShelter(Guid id)
        {
            var shelter = _getShelterById.GetById(id);

            return View("EditShelter", shelter);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public IActionResult EditShelter(ShelterModel model)
        {
            _editShelter.EditShelter(model);

            return Redirect("/Shelter/Index");
        }        
    }
}

AnimalRescue/Views/Shelter/AddShelter.cshtml
@model ShelterModel

@*<a asp-controller="Home" asp-action="Index">Home</a>*@


<div class="user-profile">

    <div class="profile-content">

        <form asp-controller="Shelter" asp-action="AddShelter" method="post">
            <div>
                <p>
                    <div>
                        @Html.LabelFor(x=>x.Name, "Название")<br />
                        <input asp-for="Name" class="profile-item" />
                    </div>
                </p>
            </div>
            <div>
                <p>
                    <div>
                        @Html.LabelFor(x=>x.Address, "Адрес")<br />
                        <input asp-for="Address" class="profile-item" />
                    </div>
                </p>
            </div>
            
            <p>
                <div>
                    <input class="input-logon-logof" type="submit" value="Добавить" />
                </div>
            </p>
        </form>
    </div>

</div>

AnimalRescue/Views/Shelter/EditShelter.cshtml
@model ShelterModel

<div class="chapter-title">
    <h1> Изменить профиль приюта</h1>
</div>


<form asp-controller ="Shelter" asp-action="EditShelter" method="post" name="EditShelter">
    <div>
        <p>
            @Html.LabelFor(x=>x.Name, "название приюта")<br />
            @Html.EditorFor(x=>x.Name)

            @Html.LabelFor(x=>x.Address, "адрес приюта")<br />
            @Html.EditorFor(x=>x.Address)

            <button type="submit">SAVE</button>
        </p>
    </div>
</form>

AnimalRescue/Views/Shelter/Index.cshtml
@model ShelterModel
@{
    var sheltersList = (List<ShelterModel>)ViewData["AllShelters"];
}



<div class="chapter-title">
    <h1>Список приютов</h1>
</div>


@if (sheltersList.Count != 0)
{
    <div>
        <table>           
            @foreach (var item in sheltersList)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Address</td>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
                    {
                        <td>
                            <form asp-controller="Shelter" asp-action="RemoveShelter" asp-route-id="@item.Id" method="post" name="DleteShelter">
                                <div>
                                    <input class="shelter-operations" type="submit" value="Удалить" />
                                </div>
                            </form>

                        </td>
                        <td>
                            <form asp-controller="Shelter" asp-action="EditShelter" asp-route-id="@item.Id" method="get" name="EditShelter">
                                <div>
                                    <input class="shelter-operations" type="submit" value="Изменить" />
                                </div>
                            </form>
                        </td>
                        <td>
                            <form asp-controller="Animal" asp-action="AddPet" asp-route-id="@item.Id" method="get" name="AddPet">
                                <div>
                                    <input class="shelter-operations" type="submit" value="Новый" />
                                </div>
                            </form>

                        </td>
                    }
                    <td>
                        <form asp-controller="Animal" asp-action="DisplayShelterPets" asp-route-id="@item.Id" method="get" name="DisplayShelterPets">
                            <div>
                                <input class="shelter-operations" type="submit" value="Обитатели" />
                            </div>
                        </form>

                    </td>
                </tr>
                
            }
                      
        </table>
    </div>
}