AnimalRescue/Controllers/AdminController.cs
using AnimalRescue.Models;
using AnimalRescue.Services.DBServices.Interfaces;
using AnimalRescue.Services.UserSevices.Interfaces;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace AnimalRescue.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        private readonly IGetUserByEmail _getUserByEmail;

        public AdminController(IGetUserByEmail getUserByEmail)
        {
            _getUserByEmail = getUserByEmail;
        }
        public IActionResult Index()
        {
            var login = User.Identity.Name;

            ViewData["UserProfile"] = _getUserByEmail.GetUserModel(login);

            return View();
        }

        
        //public IActionResult Admin()
        //{
        //    return View();
        //}

        //[Authorize(Roles = "user")]
        //public IActionResult User()
        //{
        //    return View();
        //}        
    }
}

AnimalRescue/Controllers/AuthController.cs
using AnimalRescue.Models;
using AnimalRescue.Services.DBServices.Interfaces;
using AnimalRescue.Services.UserSevices.Interfaces;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace AnimalRescue.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAnimalRescueDbContext _dbContext;
        private readonly IAddUser _createNewUser;

        public AuthController(IAnimalRescueDbContext dbContext,
                              IAddUser createNewUser)
        {
            _dbContext = dbContext;
            _createNewUser = createNewUser;
        }

        [AllowAnonymous]
        public IActionResult Login(string returnUrl)
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await _dbContext.animalRescueDBContext.Users
                       .SingleOrDefaultAsync(u => u.Email == model.EMail && u.Password == model.Password);

            if (user == null)
            {
                ModelState.AddModelError("", "User not found");
                return View(model);
            }

            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, model.EMail),
                new Claim(ClaimTypes.Role, user.Role),
            };
            var claimIdentity = new ClaimsIdentity(claims, "Cookie");
            var claimPrincipal = new ClaimsPrincipal(claimIdentity);
            await HttpContext.SignInAsync("Cookie", claimPrincipal);

            //if (model.ReturnUrl == null)
            //{
            //    model.ReturnUrl = $"/{user.Role}/index";
            //}

            model.ReturnUrl = $"/{user.Role}/index";

            return Redirect(model.ReturnUrl);
        }

        [AllowAnonymous]
        public IActionResult Register()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Register(UserModel user)
        {
            _createNewUser.CreateUser(user);

            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, user.Email),
                new Claim(ClaimTypes.Role, user.Role),
            };
            var claimIdentity = new ClaimsIdentity(claims, "Cookie");
            var claimPrincipal = new ClaimsPrincipal(claimIdentity);
            await HttpContext.SignInAsync("Cookie", claimPrincipal);

           
            return Redirect("/User/Index");
        }

        public IActionResult LogOff()
        {
            HttpContext.SignOutAsync("Cookie");
            return Redirect("/Home/Index");
        }
    }
}

AnimalRescue/Controllers/PostController.cs
using AnimalRescue.Exceptions;
using AnimalRescue.Models;
using AnimalRescue.Services.DBServices.Interfaces;
using AnimalRescue.Services.FileUploadServices.Interfaces;
using AnimalRescue.Services.PostServices.Interfaces;
using AnimalRescue.Services.UserSevices;
using AnimalRescue.Services.UserSevices.Interfaces;
using AnimalRescueDBModels.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.EntityFrameworkCore;
using Microsoft.Net.Http.Headers;
using System.Data;
using System.Security.Claims;

namespace AnimalRescue.Controllers
{
    [Authorize]
    public class PostController : Controller
    {

        private readonly IFileUpload _fileUpload;
        private readonly IGetUserByEmail _getUserByEmail;
        private readonly IAnimalRescueDbContext _dbContext;
        private readonly IAddPost _addPost;
        private readonly IDeletePost _removePost;
        private readonly IGetUserPosts _getUserPosts;
        public string filePath;

        public PostController(IFileUpload fileUpload,
                              IGetUserByEmail getUserByEmail,
                              IAnimalRescueDbContext dbContext,
                              IAddPost addPost,
                              IDeletePost removePost,
                              IGetUserPosts getUserPosts) 
        {
            _fileUpload = fileUpload;
            _getUserByEmail = getUserByEmail;
            _dbContext = dbContext;
            _addPost = addPost;
            _removePost = removePost;
            _getUserPosts = getUserPosts;
        }


        [HttpGet]
        public IActionResult AddPost()
        {
            var eMail = User.Identity.Name;

            ViewData["UserId"] = _getUserByEmail.GetUserModel(eMail).Id;
            return View();
        }


        [Authorize]
        [HttpPost]
        public async Task<ActionResult> AddPost(PostModel model) 
        {

            model.Id = Guid.NewGuid();
            var repoPath = $"wwwroot\\Repo\\Posts\\{model.Id}";

            if (model.File != null)
            {
                filePath = await _fileUpload.UploadFileAsync(model.File, repoPath, model.Id.ToString());
            }
            else 
            {
                throw new FileUploadExeption("You have not uploaded an image!!!Please do this!!!");
            }

            model.Type = model.Type;
            model.Description = model.Description;
            model.UserId = model.UserId;

            _addPost.CreatePost(model);

            return Redirect("/Home/Index");

        }

        [Authorize]
        [HttpPost]
        public IActionResult DeletePost(PostModel postModel) 
        {
            _removePost.RemovePost(postModel.Id);

            return Redirect("/Post/DisplayUserPosts");
        }

        [Authorize]
        [HttpPost]
        public IActionResult DeletePostFromBoard(PostModel postModel)
        {
            _removePost.RemovePost(postModel.Id);

            return Redirect("/Home/Index");
        }

        [Authorize]
        [HttpGet]
        public IActionResult DisplayUserPosts() 
        {
            var email = User.Identity.Name;
            var userId = _getUserByEmail.GetUserModel(email).Id;

            ViewData["UserPosts"] = _getUserPosts.GetPosts(userId);

            return View();
        }
    }
}

AnimalRescue/Controllers/UserController.cs
using AnimalRescue.Models;
using AnimalRescue.Services.UserSevices;
using AnimalRescue.Services.UserSevices.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace AnimalRescue.Controllers
{
    
    public class UserController : Controller
    {
        private readonly IGetUserByEmail _getUserByEmail;
        private readonly IEditUser _editUser;
        private readonly IGetAllUsers _getAllUsers;
        private readonly IDeleteUser _deleteUser;

        public UserController(IGetUserByEmail getUserByEmail,
                              IEditUser editUser,
                              IGetAllUsers getAllUsers,
                              IDeleteUser deleteUser)
        {
            _getUserByEmail = getUserByEmail;
            _editUser = editUser;
            _getAllUsers = getAllUsers;
            _deleteUser = deleteUser;
        }

        [Authorize(Roles = "user")]
        public IActionResult Index()
        {
            var login = User.Identity.Name;

            ViewData["UserProfile"] = _getUserByEmail.GetUserModel(login);

            return View();
        }

        [Authorize(Roles = "user")]
        [HttpPost]
        public IActionResult EditUserProperties(UserModel user) 
        {
            _editUser.EditUser(user);

            return Redirect("/User/Index");
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public IActionResult DisplayUsers() 
        {
            ViewData["AllUsersList"] = _getAllUsers.GetAllUsers();

            return View();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public IActionResult DeleteUser(UserModel userModel) 
        {
            _deleteUser.DeleteUser(userModel.Id);

            return Redirect("/User/DisplayUsers");
        }
    }
}

AnimalRescue/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
 @*   <title>@ViewData["Title"] - AnimalRescue</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AnimalRescue.styles.css" asp-append-version="true" />*@
    <link type="text/css" rel="stylesheet" href="~/css/style.css" />
</head>
<body>
    <header>
        <div class="head-back">
            <div classe="header-content">
                <div class="logo">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><img class="graficlogo" src="/img/logo.png" alt="lgo"></a>
                    
                    @if (User.Identity.IsAuthenticated) 
                    {
                        <div class="buttons-logon-logoff">
                            <input class="input-logon-logof" type="button" value="ВЫХОД" onclick="location.href='@Url.Action("LogOff", "Auth")'" />
                        </div>                        
                    }
                    else
                    {
                        <div class="buttons-logon-logoff">
                            <div>
                                <input class="input-logon-logof" type="button" value="Вход" onclick="location.href='@Url.Action("Index", "User")'" />
                            </div>
                            <div>
                                <input class="input-logon-logof" type="button" value="Регистрация" onclick="location.href='@Url.Action("Register", "Auth")'" />
                            </div>
                        </div>
                    }
                    
                </div>
            </div>
            <nav>
                <div class="topnav">
                    <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">ГЛАВНАЯ</a>
                    <a class="nav-link text-dark" asp-controller="Post" asp-action="AddPost">РАЗМЕСТИТЬ ОБЪЯВЛЕНИЕ</a>
                    <a class="nav-link text-dark" asp-controller="Shelter" asp-action="Index">ПРИЮТЫ</a>
                </div>
            </nav>

            @if (User.Identity.IsAuthenticated)
            {
                <nav class="small-nav">
                    <div class="topnav-small-nav">
                        @if (User.IsInRole("admin"))
                        {
                            <a asp-controller="Admin" asp-action="Index">ПРОФИЛЬ</a>
                            <a class="nav-link text-dark" asp-controller="Shelter" asp-action="AddShelter">ДОБАВИТЬ ПРИЮТ</a>
                            <a class="nav-link text-dark" asp-controller="Post" asp-action="DisplayUserPosts">МОИ ОБЪЯВЛЕНИЯ</a>
                            <a class="nav-link text-dark" asp-controller="User" asp-action="DisplayUsers">СПИСОК ПОЛЬЗОВАТЕЛЕЙ</a>
                        }
                        else if (User.IsInRole("user"))
                        {
                            <a asp-controller="User" asp-action="Index">МОЙ ПРОФИЛЬ</a>
                            <a class="nav-link text-dark" asp-controller="Post" asp-action="DisplayUserPosts">МОИ ОБЪЯВЛЕНИЯ</a>
                            <a class="nav-link text-dark" asp-controller="Favorites" asp-action="DisplayFavorites">ИЗБРАННОЕ</a>
                        }
                    </div>
                </nav>
            }
            
        </div>
    </header>
    @*<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AnimalRescue</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
    <ul class="navbar-nav flex-grow-1">
    <li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
    </li>
    <li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </li>
    </ul>
    </div>
    </div>
    </nav>
    </header>*@
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class="info">
        <footer>
            <a class="info-text">&#9993 info@mail.inf<br>&#128383 +1-111-11-11-111<br>&#128383 +2-222-22-22-222</a>
        </footer>
    </div>
    @*    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)*@
</body>
</html>