AnimalRescue/Controllers/AnimalController.cs
using AnimalRescue.Exceptions;
using AnimalRescue.Models;
using AnimalRescue.Services.AnimalServices.Interfaces;
using AnimalRescue.Services.FavoriteServices.Interfaces;
using AnimalRescue.Services.FileUploadServices.Interfaces;
using AnimalRescue.Services.UserSevices.Interfaces;
using AnimalRescueDBModels.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AnimalRescue.Controllers
{
    public class AnimalController : Controller
    {
        private readonly IGetShelterAnimals _getShelterAnimals;
        private readonly IAddAnimal _addAnimal;
        private readonly IFileUpload _fileUpload;
        private readonly IGetUserByEmail _getUserByEmail;
        private readonly IGetUserFavorites _getUserFavorites;
        private readonly IDeleteAnimal _deleteAnimal;
        public string filePath;

        public AnimalController(IGetShelterAnimals getShelterAnimals,
                                IAddAnimal addAnimal,
                                IFileUpload fileUpload,
                                IGetUserByEmail getUserByEmail,
                                IGetUserFavorites getUserFavorites,
                                IDeleteAnimal deleteAnimal)
        {
            _getShelterAnimals = getShelterAnimals;
            _addAnimal = addAnimal;
            _fileUpload = fileUpload;
            _getUserByEmail = getUserByEmail;
            _getUserFavorites = getUserFavorites;
            _deleteAnimal = deleteAnimal;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult DisplayShelterPets(ShelterModel shelter)
        {
            if (User.Identity.IsAuthenticated) 
            {
                var user = _getUserByEmail.GetUserModel(User.Identity.Name);
                var favoritesList = _getUserFavorites.GetFavorites(user.Id);

                ViewData["SelectedUserFavorites"] = favoritesList;
            }

            var animals = _getShelterAnimals.GetAnimals(shelter.Id);
            ViewData["ShelterAnimals"] = animals;

            return View();
        }

        [HttpGet]
        [Authorize(Roles ="admin")]
        public IActionResult AddPet(ShelterModel shelter) 
        {
            ViewData["ShelterId"] = shelter.Id.ToString();

            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<ActionResult> AddPet(AnimalModel animal)
        {
            var repoPath = $"wwwroot\\Repo\\Animals\\{animal.ShelterId}";

            if (animal.File != null)
            {
                filePath = await _fileUpload.UploadFileAsync(animal.File, repoPath, animal.Id.ToString());
            }
            else
            {
                throw new FileUploadExeption("You have not uploaded an image!!!Please do this!!!");
            }
            
            animal.Id = Guid.NewGuid();
            animal.PhotoFileName = $"{animal.Id}{Path.GetExtension(animal.File.FileName)}";

            _addAnimal.CreateAnimal(animal);
            
            return Redirect("/Shelter/Index");
        }


        public IActionResult DeleteAnimal(AnimalModel animalModel) 
        {
            _deleteAnimal.DeleteAnimal(animalModel);

            return Redirect("/Shelter/Index");
        }
    }
}

AnimalRescue/Controllers/FavoritesController.cs
using AnimalRescue.Models;
using AnimalRescue.Services.AnimalServices.Interfaces;
using AnimalRescue.Services.FavoriteServices.Interfaces;
using AnimalRescue.Services.ShelterServices.Interfaces;
using AnimalRescue.Services.UserSevices.Interfaces;
using AnimalRescueDBModels.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AnimalRescue.Controllers
{
    public class FavoritesController : Controller
    {
        private readonly IAddFavorite _addFovorite;
        private readonly IGetUserByEmail _getUserByEmail;
        private readonly IGetShelterAnimals _getShelterAnimals;
        private readonly IGetFavoritesModels _getFavoritesModels;
        private readonly IDeleteFavorite _deleteFavorite;

        public FavoritesController(IAddFavorite addFovorite,
                                   IGetUserByEmail getUserByEmail,
                                   IGetShelterAnimals getShelterAnimals,
                                   IGetFavoritesModels getFavoritesModels,
                                   IDeleteFavorite deleteFavorite)
        {
            _addFovorite = addFovorite;
            _getUserByEmail = getUserByEmail;
            _getShelterAnimals = getShelterAnimals;
            _getFavoritesModels = getFavoritesModels;
            _deleteFavorite = deleteFavorite;
        }

        [Authorize(Roles ="user")]
        [HttpPost]
        public IActionResult AddFavorite(AnimalModel animal)
        {
            var animalId = animal.Id;
            var userId = _getUserByEmail.GetUserModel(User.Identity.Name).Id;
            
            _addFovorite.SetFavorite(userId, animalId);

            //var animals = _getShelterAnimals.GetAnimals(animal.ShelterId);
            //ViewData["ShelterAnimals"] = animals;

            return Redirect("/Shelter/Index");
        }

        [Authorize(Roles ="user")]
        [HttpGet]
        public IActionResult DisplayFavorites() 
        {
            var userId = _getUserByEmail.GetUserModel(User.Identity.Name).Id;
            var favorites = _getFavoritesModels.GetFavoriteModelList(userId);

            ViewData["UserFavorites"] = favorites;

            return View();
        }

        [Authorize(Roles = "user")]
        [HttpPost]
        public IActionResult DeleteFavorite(FavoriteModel model)
        {
            _deleteFavorite.RemoveFavorite(model.AnimalId);

            return Redirect("/Favorites/DisplayFavorites");
        }
    }
}

AnimalRescue/Views/Animal/AddPet.cshtml
@model AnimalModel

<div class="chapter-title">
    <h1>Добавить новое животное в приют</h1>
</div>



<div class="user-profile">
    <div class="profile-content">
        <form asp-controller="Animal" asp-action="AddPet" method="post" name="AddPet" enctype="multipart/form-data">
            <div class="mb-3">
                @Html.LabelFor(x=>x.Type, "Загрузите фото")<br />
                <input type="file" name="file" class="file-upload" />
            </div>
            <div>
                @Html.LabelFor(x=>x.Type, "Тип животного")<br />
                <input asp-for="Type" class="profile-item" />
            </div>
            <div>
                @Html.LabelFor(x=>x.Type, "Имя")<br />
                <input asp-for="Name" class="profile-item" />
            </div>
            <div>
                @Html.LabelFor(x=>x.Type, "Пол")<br />
                <input asp-for="Gender" class="profile-item" />
            </div>
            <div>
                @Html.LabelFor(x=>x.Type, "Возраст")<br />
                <input type="number" asp-for="Age" class="profile-item" />
            </div>
            <div>
                @Html.LabelFor(x=>x.Type, "Описание")<br />
                <textarea asp-for="Description"></textarea>
            </div>
            <div>
                <input type="hidden" asp-for="ShelterId" value=@ViewData["ShelterId"] />
                <input class="input-logon-logof" type="submit" value="Добавить" />
            </div>
        </form>
    </div>
</div>

AnimalRescue/Views/Animal/DisplayShelterPets.cshtml
@model AnimalModel
@{
    var animals = (List<AnimalModel>)ViewData["ShelterAnimals"];

    bool isMatch;
}
<div class="chapter-title">
    <h1>Обитатели приюта</h1>
</div>

<div>
    @foreach (var animal in animals)
    {
        isMatch = false;       

        <div class="declaration">

        @if (User.Identity.IsAuthenticated && User.IsInRole("admin")) 
        {
            <div>
                <form asp-controller="Animal" asp-action="DeleteAnimal" asp-route-id="@animal.Id" method="post" name="DeletePost">
                    <input type="hidden" asp-for="ShelterId" value=@animal.ShelterId />
                    <button type="submit" class="btn btn-sm btn-danger">
                        Удалить
                    </button>
                </form>
            </div>
        }
        

        <div class="pet-photo">
            <img src='@Url.Content($"~/Repo/Animals/{animal.ShelterId}/{animal.PhotoFileName}")' class="image-pet" alt="photo">
        </div>
        <div class="params">
                <div>
                    <a class="description">@animal.Name</a>
                </div>
                <div>
                    <a class="description">@animal.Type</a>
                </div>
                <div>
                    <a class="description">@animal.Age</a>
                </div>
                <div>
                    <a class="description">@animal.Gender</a>
                </div>
                <div>
                    <a class="description">@animal.Description</a>
                </div>
        </div>

        @if (ViewData["SelectedUserFavorites"] != null)
        {
            foreach (var item in (List<AnimalUserModel>)ViewData["SelectedUserFavorites"])
            {
                if (item.AnimalId == animal.Id) 
                {
                    isMatch = true;
                    break;
                }
            }
        }
        @if (User.Identity.IsAuthenticated && User.IsInRole("user")) 
        {
            <form asp-controller="Favorites" asp-action="AddFavorite" method="post">
                <input type="hidden" asp-for="Id" value=@animal.Id />
                <input type="hidden" asp-for="ShelterId" value=@animal.ShelterId />
                @if (isMatch)
                {
                    <h3>Уже отслеживаете</h3>
                }
                else
                {
                    <input disabled=@isMatch class="input-button" type="submit" value="Избранное" />
                }
            </form>            
        }
        </div>
    }
</div>